version: 2.1

orbs:
  maven: circleci/maven@1.2.0

parameters:
  build-orders:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: The First Step for orders
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step for orders
          command: |
            ls -al
            echo '^^^The files in your repo^^^'

workflows:

  orders:
    when: << pipeline.parameters.build-orders >>
    jobs:
      - build
