version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: The First Step for orders
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step for orders
          command: |
            ls -al
            echo '^^^The files in your repo^^^'

workflows:
  # Name of workflow
  monorepo-orders-build:
    # List of jobs that will run
    jobs:
      - build