version: 2.1

orbs:
  maven: circleci/maven@1.2.0

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  build-users:
    type: boolean
    default: false

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
  # when pipeline parameter, run-build-service-1-job is true, the
  # build-service-1 job is triggered.
  users:
    when: << pipeline.parameters.build-users >>
    jobs:
      build:
        docker:
          - image: alpine:3.15
        steps:
          - checkout
          - run:
              name: The First Step for users
              command: |
                echo 'Hello World!'
                echo 'This is the delivery pipeline'
          - run:
              name: The Second Step for users
              command: |
                ls -al
                echo '^^^The files in your repo^^^'
  # when pipeline parameter, run-build-service-2-job is true, the
  # build-service-2 job is triggered.