version: '2.1'

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.7
  dynamic: bjd2385/dynamic-continuation@3.8.1

workflows:
  on-commit:
    jobs:
      - dynamic/continue:
          base-revision: main
          context: circleci
          modules: |
            /users
            /orders
