version: '2.1'
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.7
workflows:
  generate-config:
    jobs:
      #      - path-filtering/filter:
      #          base-revision: main
      #          config-path: .circleci/continue_config.yml
      #          mapping: |
      #            orders/.* build-order true
      #            users/.* build-users true
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/build-users-config.yml
          mapping: |
            users/.* build-users true .circleci/build-users-config.yml
#            orders/.* build-orders true .circleci/build-orders-config.yml
#      - path-filtering/filter:
#          base-revision: main
#          config-path: .circleci/continue-config.yml
#          mapping: .circleci/mapping.conf
